### ISSUE TITLE
Issues with Upload

### ISSUE THREAD

**Issue by ibuteb** [mroote/factorio-server-manager#118]
Hey there,
i like this server manager but unfortunately am i not able to get the mod upload to work, is there anyone who can give me a hand?
i have debian and i also installed the dependecies go and nodejs
as soon as i start an upload i get a error message: "something went wron with the file upload operation"
and the follow console output: 

2018/08/04 01:26:27 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:27 http: panic serving 188.102.76.32:29973: runtime error: index out of range
goroutine 36 [running]:
net/http.(*conn).serve.func1(0xc4209d0140)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc4200ad7d0, 0x30, 0x89fca0, 0xc42020c410, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc4200ad7d0, 0x30, 0x89fca0, 0xc42020c410, 0xc42013c150, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc420087930, 0xc42013c150, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc42013c150, 0xc4209d5730, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc42017eba0, 0xc42017eba0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.listInstalledModsHandler(0x89e540, 0xc4201182a0, 0xc42012ad00)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:26 +0xc2
net/http.HandlerFunc.ServeHTTP(0x867188, 0x89e540, 0xc4201182a0, 0xc42012ad00)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc4201182a0, 0xc42012ad00)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182480, 0x89e540, 0xc4201182a0, 0xc42012ad00)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc4201182a0, 0xc42012ad00)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc4201182a0, 0xc42014ed00)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4209d0140, 0x89e900, 0xc42015ad40)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/04 01:26:27 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:27 http: panic serving 188.102.76.32:29975: runtime error: index out of range
goroutine 27 [running]:
net/http.(*conn).serve.func1(0xc420092820)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc42022ab40, 0x30, 0x89fca0, 0xc42020d110, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc42022ab40, 0x30, 0x89fca0, 0xc42020d110, 0xc42013c500, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc42020c750, 0xc42013c500, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc42013c500, 0xc4209d9730, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc42017f1a0, 0xc42017f1a0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.listInstalledModsHandler(0x89e540, 0xc420118460, 0xc42012b200)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:26 +0xc2
net/http.HandlerFunc.ServeHTTP(0x867188, 0x89e540, 0xc420118460, 0xc42012b200)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc420118460, 0xc42012b200)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182480, 0x89e540, 0xc420118460, 0xc42012b200)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc420118460, 0xc42012b200)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc420118460, 0xc42012b000)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420092820, 0x89e900, 0xc420071780)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/04 01:26:27 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:27 http: panic serving 188.102.76.32:29974: runtime error: index out of range
goroutine 25 [running]:
net/http.(*conn).serve.func1(0xc4201af220)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc42026c060, 0x30, 0x89fca0, 0xc420123930, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc42026c060, 0x30, 0x89fca0, 0xc420123930, 0xc420149a20, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc420122ea0, 0xc420149a20, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc420149a20, 0xc4200a9730, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc4201bdb30, 0xc4201bdb30, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.listInstalledModsHandler(0x89e540, 0xc4201c8380, 0xc42014ef00)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:26 +0xc2
net/http.HandlerFunc.ServeHTTP(0x867188, 0x89e540, 0xc4201c8380, 0xc42014ef00)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc4201c8380, 0xc42014ef00)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182480, 0x89e540, 0xc4201c8380, 0xc42014ef00)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc4201c8380, 0xc42014ef00)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc4201c8380, 0xc42014eb00)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4201af220, 0x89e900, 0xc420166440)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/04 01:26:27 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:27 http: panic serving 188.102.76.32:29976: runtime error: index out of range
goroutine 42 [running]:
net/http.(*conn).serve.func1(0xc4209ec640)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc42022be90, 0x30, 0x89fca0, 0xc42020de10, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc42022be90, 0x30, 0x89fca0, 0xc42020de10, 0xc42013c7f0, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc42020d450, 0xc42013c7f0, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc42013c7f0, 0xc4209d9730, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc42017f890, 0xc42017f890, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.listInstalledModsHandler(0x89e540, 0xc420118620, 0xc42012b500)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:26 +0xc2
net/http.HandlerFunc.ServeHTTP(0x867188, 0x89e540, 0xc420118620, 0xc42012b500)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc420118620, 0xc42012b500)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182480, 0x89e540, 0xc420118620, 0xc42012b500)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc420118620, 0xc42012b500)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc420118620, 0xc42014ec00)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4209ec640, 0x89e900, 0xc420166a00)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/04 01:26:27 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:27 http: panic serving 188.102.76.32:29977: runtime error: index out of range
goroutine 30 [running]:
net/http.(*conn).serve.func1(0xc420093220)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc42026d3b0, 0x30, 0x89fca0, 0xc4202aa680, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc42026d3b0, 0x30, 0x89fca0, 0xc4202aa680, 0xc420149ce0, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc420123c70, 0xc420149ce0, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc420149ce0, 0xc4200a9730, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc4201561b0, 0xc4201561b0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.listInstalledModsHandler(0x89e540, 0xc4201c8540, 0xc42014f100)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:26 +0xc2
net/http.HandlerFunc.ServeHTTP(0x867188, 0x89e540, 0xc4201c8540, 0xc42014f100)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc4201c8540, 0xc42014f100)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182480, 0x89e540, 0xc4201c8540, 0xc42014f100)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc4201c8540, 0xc42014f100)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc4201c8540, 0xc42012b300)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420093220, 0x89e900, 0xc42015a3c0)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/04 01:26:27 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:27 http: panic serving 188.102.76.32:29978: runtime error: index out of range
goroutine 32 [running]:
net/http.(*conn).serve.func1(0xc4200935e0)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc4202c2720, 0x30, 0x89fca0, 0xc4202ab380, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc4202c2720, 0x30, 0x89fca0, 0xc4202ab380, 0xc420149fc0, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc4202aa9c0, 0xc420149fc0, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc420149fc0, 0xc4200a9730, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc420156b40, 0xc420156b40, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.listInstalledModsHandler(0x89e540, 0xc4201c8700, 0xc42014f300)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:26 +0xc2
net/http.HandlerFunc.ServeHTTP(0x867188, 0x89e540, 0xc4201c8700, 0xc42014f300)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc4201c8700, 0xc42014f300)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182480, 0x89e540, 0xc4201c8700, 0xc42014f300)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc4201c8700, 0xc42014f300)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc4201c8700, 0xc42012b600)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4200935e0, 0x89e900, 0xc42015a7c0)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/04 01:26:27 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:27 http: panic serving 188.102.76.32:29979: runtime error: index out of range
goroutine 33 [running]:
net/http.(*conn).serve.func1(0xc420093720)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc4202c3a70, 0x30, 0x89fca0, 0xc4202f00d0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc4202c3a70, 0x30, 0x89fca0, 0xc4202f00d0, 0xc4202ca280, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc4202ab6c0, 0xc4202ca280, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc4202ca280, 0xc4200a9730, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc420157170, 0xc420157170, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.listInstalledModsHandler(0x89e540, 0xc4201c88c0, 0xc42014f500)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:26 +0xc2
net/http.HandlerFunc.ServeHTTP(0x867188, 0x89e540, 0xc4201c88c0, 0xc42014f500)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc4201c88c0, 0xc42014f500)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182480, 0x89e540, 0xc4201c88c0, 0xc42014f500)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc4201c88c0, 0xc42014f500)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc4201c88c0, 0xc42012b700)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420093720, 0x89e900, 0xc42015a840)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/04 01:26:27 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:27 http: panic serving 188.102.76.32:29980: runtime error: index out of range
goroutine 50 [running]:
net/http.(*conn).serve.func1(0xc420093860)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc42028d200, 0x30, 0x89fca0, 0xc42030ab60, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc42028d200, 0x30, 0x89fca0, 0xc42030ab60, 0xc42013cae0, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc42030a1a0, 0xc42013cae0, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc42013cae0, 0xc4209d9730, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc42030c150, 0xc42030c150, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.listInstalledModsHandler(0x89e540, 0xc4201187e0, 0xc42012ba00)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:26 +0xc2
net/http.HandlerFunc.ServeHTTP(0x867188, 0x89e540, 0xc4201187e0, 0xc42012ba00)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc4201187e0, 0xc42012ba00)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182480, 0x89e540, 0xc4201187e0, 0xc42012ba00)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc4201187e0, 0xc42012ba00)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc4201187e0, 0xc42012b800)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420093860, 0x89e900, 0xc42015a8c0)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/04 01:26:27 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:27 http: panic serving 188.102.76.32:29981: runtime error: index out of range
goroutine 47 [running]:
net/http.(*conn).serve.func1(0xc4209ed180)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc420330de0, 0x30, 0x89fca0, 0xc4202f0dd0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc420330de0, 0x30, 0x89fca0, 0xc4202f0dd0, 0xc4202ca550, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc4202f0410, 0xc4202ca550, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc4202ca550, 0xc4200a9730, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc420157860, 0xc420157860, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.listInstalledModsHandler(0x89e540, 0xc4201c8a80, 0xc42014f800)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:26 +0xc2
net/http.HandlerFunc.ServeHTTP(0x867188, 0x89e540, 0xc4201c8a80, 0xc42014f800)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc4201c8a80, 0xc42014f800)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182480, 0x89e540, 0xc4201c8a80, 0xc42014f800)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc4201c8a80, 0xc42014f800)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc4201c8a80, 0xc42014f600)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4209ed180, 0x89e900, 0xc420167740)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/04 01:26:27 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:27 http: panic serving 188.102.76.32:29982: runtime error: index out of range
goroutine 52 [running]:
net/http.(*conn).serve.func1(0xc420093c20)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc420358570, 0x30, 0x89fca0, 0xc42030b860, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc420358570, 0x30, 0x89fca0, 0xc42030b860, 0xc42013cdb0, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc42030aea0, 0xc42013cdb0, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc42013cdb0, 0xc4209d9730, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc42030c840, 0xc42030c840, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.listInstalledModsHandler(0x89e540, 0xc4201189a0, 0xc42012bd00)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:26 +0xc2
net/http.HandlerFunc.ServeHTTP(0x867188, 0x89e540, 0xc4201189a0, 0xc42012bd00)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc4201189a0, 0xc42012bd00)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182480, 0x89e540, 0xc4201189a0, 0xc42012bd00)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc4201189a0, 0xc42012bd00)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc4201189a0, 0xc42012bb00)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420093c20, 0x89e900, 0xc42015aec0)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/04 01:26:48 error finding basemodDependency. Using FactorioVersion...
2018/08/04 01:26:48 http: panic serving 188.102.76.32:29985: runtime error: index out of range
goroutine 54 [running]:
net/http.(*conn).serve.func1(0xc4201ae0a0)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7ca740, 0xa69970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc420359950, 0x30, 0x89fca0, 0xc42039a5b0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc420359950, 0x30, 0x89fca0, 0xc42039a5b0, 0xc42013d100, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc42002a840, 0x12, 0x89fca0, 0xc42030bba0, 0xc42013d100, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc42002a840, 0x12, 0xc42013d100, 0xc4209d96d0, 0x411f78)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc42030d1d0, 0xc42030d1d0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc42002a840, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.UploadModHandler(0x89e540, 0xc420118b60, 0xc42037c100)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:376 +0x124
net/http.HandlerFunc.ServeHTTP(0x867160, 0x89e540, 0xc420118b60, 0xc42037c100)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x89e540, 0xc420118b60, 0xc42037c100)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420182ce0, 0x89e540, 0xc420118b60, 0xc42037c100)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201841e0, 0x89e540, 0xc420118b60, 0xc42037c100)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420086d00, 0x89e540, 0xc420118b60, 0xc42012bf00)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4201ae0a0, 0x89e900, 0xc42015b3c0)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b

help is appreciated.
thank you
-ibuteb

**Comment by knoxfighter** [comment]
Hi,
I think this is the same error, also mentioned in #113 .
This also should be fixed with Pull Request #115 .
@mroote Isn't really active, so the fix isn't merged and released :(

**Comment by mroote** [comment]
Apologies for the delay. I've made release 0.7.4 that contains the fix in #115.

Try it out and see if that solves the issue you were seeing with mod uploads.

**Comment by ibuteb** [comment]
Hey there,
unfortunatley i still get the same errors  ... could it maybe because of a faulty GOlang installation?
if so, i did not find any good explanation on how to achive it...

2018/08/06 18:33:20 Starting server on: 0.0.0.0:8080
2018/08/06 18:33:28 error finding basemodDependency. Using FactorioVersion...
2018/08/06 18:33:28 http: panic serving 178.0.214.53:43153: runtime error: index out of range
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc420614000)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7cff00, 0xa72970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc420095260, 0x30, 0x8a6820, 0xc42013b1e0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc420095260, 0x30, 0x8a6820, 0xc42013b1e0, 0xc42008ca40, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc4200b2920, 0x12, 0x8a6820, 0xc42013a680, 0xc42008ca40, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc4200b2920, 0x12, 0xc42008ca40, 0xc4206476d0, 0x411f98)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc42018c150, 0xc42018c150, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc4200b2920, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc4200b2920, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.UploadModHandler(0x8a50c0, 0xc4200200e0, 0xc4200c6900)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:480 +0x124
net/http.HandlerFunc.ServeHTTP(0x86d7d0, 0x8a50c0, 0xc4200200e0, 0xc4200c6900)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x8a50c0, 0xc4200200e0, 0xc4200c6900)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420119640, 0x8a50c0, 0xc4200200e0, 0xc4200c6900)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42009e960, 0x8a50c0, 0xc4200200e0, 0xc4200c6900)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420093520, 0x8a50c0, 0xc4200200e0, 0xc4200c6600)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420614000, 0x8a5480, 0xc4200a1540)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/08/06 18:33:29 error finding basemodDependency. Using FactorioVersion...
2018/08/06 18:33:29 http: panic serving 178.0.214.53:43154: runtime error: index out of range
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc4200aa780)
        /usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x7cff00, 0xa72970)
        /usr/lib/go/src/runtime/panic.go:502 +0x229
main.(*ModInfoList).listInstalledMods.func1(0xc4205a86c0, 0x30, 0x8a6820, 0xc4200925b0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892
path/filepath.walk(0xc4205a86c0, 0x30, 0x8a6820, 0xc4200925b0, 0xc42015a030, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:357 +0x402
path/filepath.walk(0xc4200b2920, 0x12, 0x8a6820, 0xc42013b5f0, 0xc42015a030, 0x0, 0x10)
        /usr/lib/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc4200b2920, 0x12, 0xc42015a030, 0xc4206476d0, 0x411f98)
        /usr/lib/go/src/path/filepath/path.go:403 +0x106
main.(*ModInfoList).listInstalledMods(0xc42018cba0, 0xc42018cba0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97
main.newModInfoList(0xc4200b2920, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:37 +0xc8
main.newMods(0xc4200b2920, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:41 +0x20a
main.UploadModHandler(0x8a50c0, 0xc4200202a0, 0xc4200c6b00)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:480 +0x124
net/http.HandlerFunc.ServeHTTP(0x86d7d0, 0x8a50c0, 0xc4200202a0, 0xc4200c6b00)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
main.AuthorizeHandler.func1(0x8a50c0, 0xc4200202a0, 0xc4200c6b00)
        /home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233
net/http.HandlerFunc.ServeHTTP(0xc420119640, 0x8a50c0, 0xc4200202a0, 0xc4200c6b00)
        /usr/lib/go/src/net/http/server.go:1947 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42009e960, 0x8a50c0, 0xc4200202a0, 0xc4200c6b00)
        /home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc420093520, 0x8a50c0, 0xc4200202a0, 0xc4200c6700)
        /usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4200aa780, 0x8a5480, 0xc4200a1ac0)
        /usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2795 +0x27b

**Comment by knoxfighter** [comment]
ok, i will look into it. @ibuteb can you please provide me more informations:
- The OS, the server-manager runs on
- The browser you used to upload the mod
- The mods you habe installed (with versions)
- The mod you tried to upload

In theory, you dont need to have GOlang installed on your system to run GO-Programs. Its like a C/C++ compiled executable, it contains direct machinecode.

**Comment by ibuteb** [comment]
Debian 9
Browser Firefox 64bit on Windows 10
Currently no mods installed
Tried to upload Squeak Through mod...

**Comment by ibuteb** [comment]
Ok, so the server manager has no dependecies?

**Comment by knoxfighter** [comment]
The dependencies are only necessary, if you want to compile it yourself. The releases includes already built executables. This executables dont have any dependencies.
Thank for more informations, i will test it now.

**Comment by ibuteb** [comment]
Great Thank you.

**Comment by knoxfighter** [comment]
The informations helped me, i fixed it know, thank you.
@mroote i fixed this bug finally. Can you accept my pull request and create a new release?

**Comment by ibuteb** [comment]
That sounds great, thank you for your effort!

**Comment by knoxfighter** [comment]
@ibuteb he already accepted it :) He just didnt made a new version^^

**Comment by ibuteb** [comment]
@knoxfighter so i have to download the code and compile it or just download 0.7.4 ? god dammit i'm a noob ;)

**Comment by knoxfighter** [comment]
@ibuteb Seems like you need to download and compile it yourself, sorry

**Comment by ibuteb** [comment]
what a pain ... :) let's see if i can handle that... @mroote don't you want to make a new version? :D

**Comment by mroote** [comment]
Yes I will make a new release with the fix this evening.

**Comment by ibuteb** [comment]
yay, i'll wait, thank you @mroote and @knoxfighter

**Comment by mroote** [comment]
I've uploaded release 0.7.5 that contains the fix.  Could you test it out and see if it resolves your issue? Thanks!

**Comment by ibuteb** [comment]
@mroote and @knoxfighter it's fixed, thank you!
